# Generated by Django 4.2.3 on 2023-07-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
